export const hotelData = [
  {
    name: "Treutel, Hagenes and Parisian",
    city: "Moneague",
    country: "Jamaica",
    description: "Luxurious hotel with stunning views",
    starRating: 5,
    pricePerNight: "79",
    type: "luxury",
    facility: "gym",
    adultCount: 1,
    childCount: 1,
  },
  {
    name: "Schaden, Considine and Wolf",
    city: "Blahodatne",
    country: "Ukraine",
    description: "Cozy boutique hotel in the heart of the city",
    starRating: 2,
    pricePerNight: "18",
    type: "Glamping",
    facility: "pool",
    adultCount: 2,
    childCount: 2,
  },
  {
    name: "Blick-Wyman",
    city: "Dongfanghong",
    country: "China",
    description: "Cozy boutique hotel in the heart of the city",
    starRating: 5,
    pricePerNight: "4635",
    type: "luxury",
    facility: "Free breakfast",
    adultCount: 3,
    childCount: 3,
  },
  {
    name: "Sawayn, Corkery and O'Conner",
    city: "Mosul",
    country: "Iraq",
    description: "Charming historic inn with elegant decor",
    starRating: 2,
    pricePerNight: "07075",
    type: "luxury",
    facility: "conference room",
    adultCount: 4,
    childCount: 4,
  },
  {
    name: "Medhurst and Sons",
    city: "Doba",
    country: "Chad",
    description: "Modern hotel with top-notch amenities",
    starRating: 1,
    pricePerNight: "3",
    type: "bed and breakfast",
    facility: "conference room",
    adultCount: 5,
    childCount: 5,
  },
  {
    name: "Cummings, Morissette and Swift",
    city: "Novoul’yanovsk",
    country: "Russia",
    description: "Luxurious hotel with stunning views",
    starRating: 5,
    pricePerNight: "400",
    type: "luxury",
    facility: "Free breakfast",
    adultCount: 6,
    childCount: 6,
  },
  {
    name: "Dach-Parker",
    city: "Orleans",
    country: "Brazil",
    description: "Cozy boutique hotel in the heart of the city",
    starRating: 3,
    pricePerNight: "7535",
    type: "Campground",
    facility: "restaurant",
    adultCount: 7,
    childCount: 7,
  },
  {
    name: "Marks-Schuster",
    city: "Gharavŭtí",
    country: "Tajikistan",
    description: "Charming historic inn with elegant decor",
    starRating: 5,
    pricePerNight: "8",
    type: "Glamping",
    facility: "Free WiFi",
    adultCount: 8,
    childCount: 8,
  },
  {
    name: "Heller-Rolfson",
    city: "Santulhão",
    country: "Portugal",
    description: "Modern hotel with top-notch amenities",
    starRating: 2,
    pricePerNight: "94566",
    type: "boutique",
    facility: "conference room",
    adultCount: 9,
    childCount: 9,
  },
  {
    name: "Kessler, Jones and Roob",
    city: "Wenquan",
    country: "China",
    description: "Charming historic inn with elegant decor",
    starRating: 5,
    pricePerNight: "91",
    type: "Glamping",
    facility: "spa",
    adultCount: 10,
    childCount: 10,
  },
];
