export const hotelTypes = [
  "Adventure",
  "B&B",
  "Campground",
  "Country Inn",
  "Eco Lodge",
  "Elegance",
  "Farmhouse",
  "Glamping",
  "Holiday Inn",
  "Holiday Resort",
  "Hotel Complex",
  "Island Resort",
  "Lakefront",
  "Lodge",
  "Montana Inn",
  "Plunge",
  "Ranch",
  "Retreat",
  "Riverfront",
  "Rustic Chic",
  "Seaside",
  "Shore",
  "Ski Resort",
  "Small Hotel",
  "Spa Resort",
  "Townhouse Hotel",
  "Treehouse",
  "Urban Oasis",
  "Village Inn",
  "Wilderness Lodge",
];

export const hotelFacilities = [
  "Free breakfast",
  "Free WiFi",
  "Parking",
  "Air Conditioning",
  "Pets allowed",
  "Restaurant",
  "Fitness center",
  "Pool",
  "Hot tub",
  "Smoking allowed",
  "Non-smoking room available",
  "Breakfast available",
  "Room service",
  "Laundry service",
  "Massage service",
  "Concierge service",
  "24-hour front desk",
  "Express check-in",
  "Express check-out",
  "Transfer service",
  "Business center",
  "Car rental",
  "Tour/ticket assistance",
  "Conference facilities",
  "Meeting/banquet facilities",
  "Doorman",
  "Lift",
  "Fitness equipment",
  "Outdoor pool",
  "Outdoor tennis courts",
  "Gym",
  "Sauna",
  "Minibar",
  "Hairdryer",
  "Indoor fireplace",
  "Terrace",
  "Beach access",
  "Fitness classes",
  "Wheelchair accessible",
  "Wheelchair ramp",
  "Babysitting/child services",
  "Kid-friendly pool",
];
